[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'cd server && npm install',
  'cd ../client && npm install'
]

[phases.build]
cmds = [
  'cd server && npm run build',
  'cd server && npx prisma generate'
]

[start]
cmd = 'cd server && npx prisma db push && npm start'