import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();

async function read(relPath) {
  return readFile(path.join(root, relPath), 'utf8');
}

test('projects exports backend shadow parity evidence artifact with integrity hash', async () => {
  const projects = await read('src/components/projects/ProjectsOperatingSystem.tsx');
  const markers = [
    "packetKind: 'backend-shadow-parity-evidence'",
    'handleExportBackendShadowParity',
    'localDomainCounts',
    "algorithm: 'sha256'",
    'computeSha256Hex(payload)',
    'Export backend mirror parity',
    'Backend mirror parity evidence exported',
    "packetKind: 'phase2b-batch1-shadow-evidence-pack'",
    'handleExportBatch1ShadowEvidencePack',
    'buildBatch1ShadowReadiness',
    'Batch 1 readiness verdict',
    "batch1Readiness.verdict === 'go' ? 'GO' : 'NO_GO'",
    'taskCalendarParity',
    'crossSurfaceParity',
    'backendMirrorParity',
    'batch1Readiness',
    'batch1ReadinessHistory',
    'batch1ReadinessCheckpoints',
    "packetKind: 'phase2b-batch1-readiness-trend'",
    'handleExportBatch1ReadinessTrend',
    'handleFreezeBatch1ReadinessSnapshot',
    'handlePromoteCheckpointToSignoff',
    "status: 'candidate'",
    "status === 'approved' ? 'APPROVED' : 'CANDIDATE'",
    'Approve signoff',
    'approverNote',
    'Approver note is required to approve signoff',
    'Checkpoint approved (',
    'selectedApprovedCheckpointId',
    'approvedBatch1Checkpoints',
    'Approved signoff checkpoint for exports',
    'No approved checkpoints',
    'signoffCheckpoint',
    'Readiness trend (last',
    'Freeze snapshot',
    'Frozen checkpoints (',
    'Export trend',
    'Frozen readiness snapshot',
    'Batch 1 readiness trend exported',
    'Export Batch 1 shadow evidence pack',
    'Batch 1 shadow evidence pack exported',
    "packetKind: 'phase2b-batch2-preflip-baseline'",
    'handleExportBatch2PreflipBaseline',
    'Approved checkpoint required before Batch 2 pre-flip export',
    'Export Batch 2 pre-flip baseline',
    'Batch 2 pre-flip baseline exported',
    'authorityRouting',
    'rolloutPlan',
    'Schedule strict',
    'Task strict',
    'Apply schedule-first strict preset',
    'Rollback authority flags',
    'Schedule-first strict preset applied',
    'Authority flags rolled back to local-only',
    "packetKind: 'phase2b-batch2-schedule-strict-proof'",
    'handleExportBatch2ScheduleStrictProof',
    'Approved checkpoint required before Batch 2 schedule-strict proof export',
    'Schedule backend + schedule strict must be ON before exporting schedule-strict proof',
    'Task strict must remain OFF during schedule-first proof export',
    'Export Batch 2 schedule strict proof',
    'Batch 2 schedule-strict proof exported',
    "packetKind: 'phase2b-batch3-preflip-baseline'",
    'handleExportBatch3PreflipBaseline',
    'Approved checkpoint required before Batch 3 pre-flip export',
    'Export Batch 3 pre-flip baseline',
    'Batch 3 pre-flip baseline exported',
    "packetKind: 'phase2b-batch3-goal-strict-proof'",
    'handleExportBatch3GoalStrictProof',
    'Approved checkpoint required before Batch 3 goal-strict proof export',
    'Goal backend + goal strict must be ON before exporting goal-strict proof',
    'Project strict must remain OFF during goal-first proof export',
    'Export Batch 3 goal strict proof',
    'Batch 3 goal-strict proof exported',
    "packetKind: 'phase2b-batch3-project-strict-proof'",
    'handleExportBatch3ProjectStrictProof',
    'Approved checkpoint required before Batch 3 project-strict proof export',
    'Goal strict must remain ON before exporting project-strict proof',
    'Project backend + project strict must be ON before exporting project-strict proof',
    'Export Batch 3 project strict proof',
    'Batch 3 project-strict proof exported',
    'Goal backend',
    'Goal strict',
    'Project backend',
    'Project strict',
    'Apply goal-first strict preset',
    'Apply project strict preset',
    'Goal-first strict preset applied',
    'Project strict preset applied',
  ];
  for (const marker of markers) {
    assert.ok(projects.includes(marker), `Missing backend parity export marker "${marker}"`);
  }
});
