"""Initial baseline

Revision ID: 75c7e2369caa
Revises: 
Create Date: 2026-03-30 18:32:24.370628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75c7e2369caa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('supported_protocols', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('capabilities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('semantic_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('endpoint_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_registry_agent_id'), 'agent_registry', ['agent_id'], unique=True)
    op.create_table('mapping_failure_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_excerpt', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_suggestion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_failure_logs_source_field'), 'mapping_failure_logs', ['source_field'], unique=False)
    op.create_index(op.f('ix_mapping_failure_logs_source_protocol'), 'mapping_failure_logs', ['source_protocol'], unique=False)
    op.create_index(op.f('ix_mapping_failure_logs_target_protocol'), 'mapping_failure_logs', ['target_protocol'], unique=False)
    op.create_table('protocol_mapping',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_protocol', sa.Enum('A2A', 'MCP', 'ACP', name='protocoltype'), nullable=False),
    sa.Column('target_protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mapping_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('semantic_equivalents', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_mapping_source_protocol'), 'protocol_mapping', ['source_protocol'], unique=False)
    op.create_table('protocol_version_delta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('protocol', sa.Enum('A2A', 'MCP', 'ACP', name='protocoltype'), nullable=False),
    sa.Column('from_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delta_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_version_delta_from_version'), 'protocol_version_delta', ['from_version'], unique=False)
    op.create_index(op.f('ix_protocol_version_delta_protocol'), 'protocol_version_delta', ['protocol'], unique=False)
    op.create_index(op.f('ix_protocol_version_delta_to_version'), 'protocol_version_delta', ['to_version'], unique=False)
    op.create_table('semantic_ontology',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rdf_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('permission_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_profiles_user_id'), 'permission_profiles', ['user_id'], unique=True)
    op.create_table('provider_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credential_type', sa.Enum('API_KEY', 'OAUTH_TOKEN', 'DELEGATED_TOKEN', name='credentialtype'), nullable=False),
    sa.Column('encrypted_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credential_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_credentials_credential_type'), 'provider_credentials', ['credential_type'], unique=False)
    op.create_index(op.f('ix_provider_credentials_provider_name'), 'provider_credentials', ['provider_name'], unique=False)
    op.create_index(op.f('ix_provider_credentials_user_id'), 'provider_credentials', ['user_id'], unique=False)
    op.create_table('tool_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('[]'::jsonb)"), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('required_permissions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_registry.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_registry_agent_id'), 'tool_registry', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tool_registry_name'), 'tool_registry', ['name'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('eat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=False)
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source_protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_agent_id', sa.UUID(), nullable=True),
    sa.Column('source_message', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('eat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'LEASED', 'RUNNING', 'COMPLETED', 'DEAD_LETTER', name='taskstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('leased_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_source_protocol'), 'tasks', ['source_protocol'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_target_agent_id'), 'tasks', ['target_agent_id'], unique=False)
    op.create_index(op.f('ix_tasks_target_protocol'), 'tasks', ['target_protocol'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasks_workflow_id'), 'tasks', ['workflow_id'], unique=False)
    op.create_table('workflow_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_schedules_next_run_at'), 'workflow_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_workflow_schedules_user_id'), 'workflow_schedules', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_schedules_workflow_id'), 'workflow_schedules', ['workflow_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'LEASED', 'RUNNING', 'ACKED', 'DEAD_LETTER', name='agentmessagestatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('leased_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_agent_id'), 'agent_messages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_status'), 'agent_messages', ['status'], unique=False)
    op.create_index(op.f('ix_agent_messages_task_id'), 'agent_messages', ['task_id'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("('{}'::jsonb)"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_created_at'), 'task_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_events_event_type'), 'task_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_event_type'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_created_at'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_agent_messages_task_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_status'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_agent_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_workflow_schedules_workflow_id'), table_name='workflow_schedules')
    op.drop_index(op.f('ix_workflow_schedules_user_id'), table_name='workflow_schedules')
    op.drop_index(op.f('ix_workflow_schedules_next_run_at'), table_name='workflow_schedules')
    op.drop_table('workflow_schedules')
    op.drop_index(op.f('ix_tasks_workflow_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_target_protocol'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_target_agent_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_source_protocol'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_tool_registry_name'), table_name='tool_registry')
    op.drop_index(op.f('ix_tool_registry_agent_id'), table_name='tool_registry')
    op.drop_table('tool_registry')
    op.drop_index(op.f('ix_provider_credentials_user_id'), table_name='provider_credentials')
    op.drop_index(op.f('ix_provider_credentials_provider_name'), table_name='provider_credentials')
    op.drop_index(op.f('ix_provider_credentials_credential_type'), table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_index(op.f('ix_permission_profiles_user_id'), table_name='permission_profiles')
    op.drop_table('permission_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('semantic_ontology')
    op.drop_index(op.f('ix_protocol_version_delta_to_version'), table_name='protocol_version_delta')
    op.drop_index(op.f('ix_protocol_version_delta_protocol'), table_name='protocol_version_delta')
    op.drop_index(op.f('ix_protocol_version_delta_from_version'), table_name='protocol_version_delta')
    op.drop_table('protocol_version_delta')
    op.drop_index(op.f('ix_protocol_mapping_source_protocol'), table_name='protocol_mapping')
    op.drop_table('protocol_mapping')
    op.drop_index(op.f('ix_mapping_failure_logs_target_protocol'), table_name='mapping_failure_logs')
    op.drop_index(op.f('ix_mapping_failure_logs_source_protocol'), table_name='mapping_failure_logs')
    op.drop_index(op.f('ix_mapping_failure_logs_source_field'), table_name='mapping_failure_logs')
    op.drop_table('mapping_failure_logs')
    op.drop_index(op.f('ix_agent_registry_agent_id'), table_name='agent_registry')
    op.drop_table('agent_registry')
    # ### end Alembic commands ###
