/**
 * AI Task Suggestion Dialog
 * 
 * Suggests 5 AI-generated tasks for an event
 * User can select one, some, or all tasks
 * Includes regenerate functionality
 */

import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { Button } from './ui/button';
import { Checkbox } from './ui/checkbox';
import { Sparkles, RefreshCw, Zap, Clock, Target } from 'lucide-react';
import { Task } from '../utils/event-task-types';
import { motion, AnimatePresence } from 'motion/react';
import { toast } from 'sonner@2.0.3';

interface SuggestedTask {
  id: string;
  title: string;
  description: string;
  estimatedTime: string;
  priority: 'high' | 'medium' | 'low';
  aiConfidence: number;
  selected: boolean;
}

interface AITaskSuggestionDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  eventTitle: string;
  eventDescription?: string;
  eventDate?: Date;
  onTasksSelected: (tasks: Partial<Task>[]) => void;
  existingTasks?: Task[];
  parentEventEndsAt?: Date; // For tasks that are becoming events
}

export function AITaskSuggestionDialog({
  open,
  onOpenChange,
  eventTitle,
  eventDescription,
  eventDate,
  onTasksSelected,
  existingTasks = [],
  parentEventEndsAt,
}: AITaskSuggestionDialogProps) {
  const [suggestedTasks, setSuggestedTasks] = useState<SuggestedTask[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationCount, setGenerationCount] = useState(0);

  // Generate tasks when dialog opens
  useEffect(() => {
    if (open && suggestedTasks.length === 0) {
      generateTasks();
    }
  }, [open]);

  const generateTasks = async () => {
    setIsGenerating(true);
    setGenerationCount(prev => prev + 1);

    // Simulate AI generation (replace with actual AI call)
    await new Promise(resolve => setTimeout(resolve, 1500));

    const taskTemplates = [
      // Preparation tasks
      { title: 'Review agenda and objectives', priority: 'high' as const, time: '15 min' },
      { title: 'Prepare presentation materials', priority: 'high' as const, time: '45 min' },
      { title: 'Set up meeting space and equipment', priority: 'medium' as const, time: '20 min' },
      { title: 'Send reminder to participants', priority: 'medium' as const, time: '10 min' },
      { title: 'Gather supporting documents', priority: 'medium' as const, time: '30 min' },
      { title: 'Coordinate with team members', priority: 'high' as const, time: '25 min' },
      { title: 'Test technical setup', priority: 'medium' as const, time: '15 min' },
      { title: 'Prepare backup plans', priority: 'low' as const, time: '20 min' },
      { title: 'Review previous action items', priority: 'medium' as const, time: '15 min' },
      { title: 'Create handout materials', priority: 'low' as const, time: '40 min' },
      { title: 'Schedule follow-up sessions', priority: 'low' as const, time: '10 min' },
      { title: 'Draft discussion questions', priority: 'medium' as const, time: '20 min' },
      { title: 'Confirm attendance', priority: 'high' as const, time: '10 min' },
      { title: 'Research background information', priority: 'medium' as const, time: '35 min' },
      { title: 'Update project documentation', priority: 'low' as const, time: '25 min' },
    ];

    // Randomize and select 5 tasks
    const shuffled = [...taskTemplates]
      .sort(() => Math.random() - 0.5)
      .slice(0, 5)
      .map((template, idx) => ({
        id: `ai-task-${Date.now()}-${idx}`,
        title: template.title,
        description: `AI-suggested task for "${eventTitle}"${parentEventEndsAt ? ' (Note: Cannot schedule after parent event ends)' : ''}`,
        estimatedTime: template.time,
        priority: template.priority,
        aiConfidence: Math.floor(Math.random() * 20 + 75), // 75-95%
        selected: false,
      }));

    setSuggestedTasks(shuffled);
    setIsGenerating(false);

    toast.success('5 tasks generated by AI', {
      description: 'Select the tasks you want to add',
      icon: <Sparkles className="w-4 h-4" />,
    });
  };

  const handleToggleTask = (taskId: string) => {
    setSuggestedTasks(prev =>
      prev.map(task =>
        task.id === taskId ? { ...task, selected: !task.selected } : task
      )
    );
  };

  const handleSelectAll = () => {
    const allSelected = suggestedTasks.every(t => t.selected);
    setSuggestedTasks(prev =>
      prev.map(task => ({ ...task, selected: !allSelected }))
    );
  };

  const handleConfirm = () => {
    const selectedTasks = suggestedTasks.filter(t => t.selected);
    
    if (selectedTasks.length === 0) {
      toast.error('No tasks selected', {
        description: 'Please select at least one task',
      });
      return;
    }

    const tasks: Partial<Task>[] = selectedTasks.map(st => ({
      id: st.id,
      title: st.title,
      description: st.description,
      completed: false,
      subtasks: [],
      resources: [],
      linksNotes: [],
      assignedTo: [],
      createdBy: 'current-user',
      createdAt: new Date(),
      updatedAt: new Date(),
      aiGenerated: true,
      aiConfidence: st.aiConfidence,
    }));

    onTasksSelected(tasks);
    onOpenChange(false);

    toast.success(`Added ${selectedTasks.length} task${selectedTasks.length > 1 ? 's' : ''}`, {
      description: 'AI-generated tasks added successfully',
      icon: <Zap className="w-4 h-4" />,
    });
  };

  const selectedCount = suggestedTasks.filter(t => t.selected).length;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-purple-500/10 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-purple-500" />
            </div>
            <div>
              <DialogTitle>AI Task Suggestions</DialogTitle>
              <DialogDescription>
                {eventTitle}
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        {/* Info Banner */}
        {parentEventEndsAt && (
          <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-3 flex items-start gap-2">
            <Clock className="w-4 h-4 text-blue-500 mt-0.5" />
            <div className="text-sm text-blue-300">
              These tasks are prep for the parent event. They cannot be scheduled after{' '}
              {parentEventEndsAt.toLocaleDateString()}.
            </div>
          </div>
        )}

        {/* Loading State */}
        {isGenerating && (
          <div className="space-y-4 py-8">
            <div className="flex flex-col items-center gap-4">
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
              >
                <Sparkles className="w-8 h-8 text-purple-500" />
              </motion.div>
              <div className="text-center">
                <p className="text-gray-300">Analyzing your event...</p>
                <p className="text-sm text-gray-500">Generating intelligent task suggestions</p>
              </div>
            </div>
            
            {/* Loading skeletons */}
            {[1, 2, 3, 4, 5].map(i => (
              <div key={i} className="bg-[#1a1f2e] rounded-lg p-4 animate-pulse">
                <div className="h-4 bg-gray-700 rounded w-3/4 mb-2" />
                <div className="h-3 bg-gray-700 rounded w-1/2" />
              </div>
            ))}
          </div>
        )}

        {/* Suggested Tasks */}
        {!isGenerating && suggestedTasks.length > 0 && (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <p className="text-sm text-gray-400">
                {selectedCount} of 5 tasks selected
              </p>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleSelectAll}
              >
                {suggestedTasks.every(t => t.selected) ? 'Deselect All' : 'Select All'}
              </Button>
            </div>

            <AnimatePresence mode="popLayout">
              {suggestedTasks.map((task, idx) => (
                <motion.div
                  key={task.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  transition={{ delay: idx * 0.05 }}
                  className={`bg-[#1a1f2e] rounded-lg p-4 border-2 transition-all cursor-pointer ${
                    task.selected
                      ? 'border-purple-500 bg-purple-500/5'
                      : 'border-transparent hover:border-gray-600'
                  }`}
                  onClick={() => handleToggleTask(task.id)}
                >
                  <div className="flex items-start gap-3">
                    <Checkbox
                      checked={task.selected}
                      onCheckedChange={() => handleToggleTask(task.id)}
                      className="mt-1"
                    />
                    
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <h4 className="text-gray-200">{task.title}</h4>
                        <div className="flex items-center gap-2">
                          <span
                            className={`text-xs px-2 py-0.5 rounded ${
                              task.priority === 'high'
                                ? 'bg-red-500/20 text-red-400'
                                : task.priority === 'medium'
                                ? 'bg-yellow-500/20 text-yellow-400'
                                : 'bg-gray-500/20 text-gray-400'
                            }`}
                          >
                            {task.priority}
                          </span>
                          <span className="text-xs text-gray-500 flex items-center gap-1">
                            <Clock className="w-3 h-3" />
                            {task.estimatedTime}
                          </span>
                        </div>
                      </div>
                      
                      <p className="text-sm text-gray-400 mt-1">{task.description}</p>
                      
                      <div className="flex items-center gap-1 mt-2">
                        <Target className="w-3 h-3 text-purple-500" />
                        <span className="text-xs text-purple-400">
                          {task.aiConfidence}% AI confidence
                        </span>
                      </div>
                    </div>
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        )}

        {/* Actions */}
        <div className="flex items-center gap-2 pt-4 border-t border-gray-800">
          <Button
            variant="outline"
            className="flex-1"
            onClick={generateTasks}
            disabled={isGenerating}
          >
            <RefreshCw className={`w-4 h-4 mr-2 ${isGenerating ? 'animate-spin' : ''}`} />
            Regenerate
          </Button>
          
          <Button
            onClick={handleConfirm}
            disabled={selectedCount === 0 || isGenerating}
            className="flex-1 bg-purple-600 hover:bg-purple-700"
          >
            <Sparkles className="w-4 h-4 mr-2" />
            Add {selectedCount > 0 ? selectedCount : ''} Task{selectedCount !== 1 ? 's' : ''}
          </Button>
        </div>

        {/* Generation Count */}
        {generationCount > 1 && (
          <p className="text-xs text-center text-gray-500">
            Generation #{generationCount}
          </p>
        )}
      </DialogContent>
    </Dialog>
  );
}
